//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKLAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class extradition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public extradition()
        {
            this.history = new HashSet<history>();
        }
    
        public int ID_выдачи { get; set; }
        public string Книга { get; set; }
        public string Отвественный { get; set; }
        public Nullable<int> Получатель { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public Nullable<System.DateTime> Дата_возврата { get; set; }
    
        public virtual books books { get; set; }
        public virtual employers employers { get; set; }
        public virtual recipient recipient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> history { get; set; }
    }
}
