//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKLAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int ID { get; set; }
        public Nullable<int> Номер_выдачи { get; set; }
        public string Наименование_книги { get; set; }
        public string Отвественный { get; set; }
        public string Получатель { get; set; }
        public string Дата_выдачи { get; set; }
        public string Дата_возврата { get; set; }
    
        public virtual extradition extradition { get; set; }
    }
}
